// Generated by ts-to-zod
import { z } from 'zod';

export const postSchema = z.object({
  data: z.object({
    date: z.string().optional(),
    title: z.string().optional(),
    mood: z.string().optional(),
    draft: z.boolean().optional(),
  }),
  content: z.string(),
});
